# Generated by Django 4.2.6 on 2023-10-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0002_alter_member_bio_alter_member_birthdate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("operations", "operations"),
                            ("education", "education"),
                            ("human resources", "human resources"),
                            ("small business", "small business"),
                            ("sales crm", "sales crm"),
                            ("engineering", "engineering"),
                            ("marketing", "marketing"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(null=True)),
                (
                    "members",
                    models.ManyToManyField(
                        null=True, related_name="wmembers", to="tascrum.member"
                    ),
                ),
            ],
        ),
    ]
