# Generated by Django 4.2.6 on 2023-10-15 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0003_workspace"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberWorkspaceRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mrole",
                        to="tascrum.member",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrole",
                        to="tascrum.workspace",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="workspace",
            name="members",
            field=models.ManyToManyField(
                related_name="wmembers",
                through="tascrum.MemberWorkspaceRole",
                to="tascrum.member",
            ),
        ),
    ]
