# Generated by Django 4.2.6 on 2023-10-15 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0004_memberworkspacerole_alter_workspace_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberworkspacerole",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tascrum.member"
            ),
        ),
        migrations.AlterField(
            model_name="memberworkspacerole",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tascrum.workspace"
            ),
        ),
    ]
