# Generated by Django 4.2.6 on 2023-10-15 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0007_board_alter_workspace_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="members",
        ),
        migrations.DeleteModel(
            name="WorkspaceMember",
        ),
        migrations.AddField(
            model_name="workspace",
            name="members",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wmembers",
                to="tascrum.member",
            ),
        ),
    ]
