# Generated by Django 4.2.6 on 2023-10-15 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0007_rename_memberworkspacerole_memberworkspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberworkspace",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mrole",
                to="tascrum.member",
            ),
        ),
        migrations.AlterField(
            model_name="memberworkspace",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wrole",
                to="tascrum.workspace",
            ),
        ),
    ]
