# Generated by Django 4.2.6 on 2023-10-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0010_memberworkspacerole_delete_memberworkspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="members",
            field=models.ManyToManyField(
                related_name="wmembers",
                through="tascrum.MemberWorkspaceRole",
                to="tascrum.member",
            ),
        ),
    ]
