# Generated by Django 4.2.6 on 2023-10-14 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occupations",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Employee", "Employee"),
                            ("Project Manager", "Project Manager"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "profimage",
                    models.ImageField(
                        default="default_profile.png", upload_to="Member/Profile"
                    ),
                ),
                ("birthdate", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
