# Generated by Django 4.2.6 on 2023-10-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MemberWorkspaceRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="member",
            name="bio",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="birthdate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="profimage",
            field=models.ImageField(
                default="default_profile.png", null=True, upload_to="Member/Profile"
            ),
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("operations", "operations"),
                            ("education", "education"),
                            ("human resources", "human resources"),
                            ("small business", "small business"),
                            ("sales crm", "sales crm"),
                            ("engineering", "engineering"),
                            ("marketing", "marketing"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(null=True)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="wmembers",
                        through="tascrum.MemberWorkspaceRole",
                        to="tascrum.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="memberworkspacerole",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tascrum.member"
            ),
        ),
        migrations.AddField(
            model_name="memberworkspacerole",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tascrum.workspace"
            ),
        ),
        migrations.CreateModel(
            name="MemberBoardRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tascrum.board"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tascrum.member"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="board",
            name="members",
            field=models.ManyToManyField(
                related_name="bmembers",
                through="tascrum.MemberBoardRole",
                to="tascrum.member",
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tascrum.workspace"
            ),
        ),
    ]
