# Generated by Django 4.2.6 on 2023-10-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='profimage',
            field=models.ImageField(default='default_profile.png', null=True, upload_to='Member/Profile'),
        ),
    ]
