# Generated by Django 4.2.6 on 2023-10-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0002_board_memberworkspacerole_alter_member_bio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="members",
        ),
        migrations.RemoveField(
            model_name="workspace",
            name="members",
        ),
    ]
