# Generated by Django 4.2.6 on 2023-10-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0002_memberworkspacerole_alter_member_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='backgroundImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
