# Generated by Django 4.2.6 on 2023-10-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0003_remove_board_members_remove_workspace_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="members",
            field=models.ManyToManyField(
                related_name="bmembers",
                through="tascrum.MemberBoardRole",
                to="tascrum.member",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="members",
            field=models.ManyToManyField(
                related_name="wmembers",
                through="tascrum.MemberWorkspaceRole",
                to="tascrum.member",
            ),
        ),
    ]
