# Generated by Django 4.2.6 on 2023-10-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0006_memberworkspacerole_delete_memberworkspace_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MemberWorkspaceRole",
            new_name="MemberWorkspace",
        ),
    ]
