# Generated by Django 4.2.6 on 2023-10-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0008_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "List",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clist",
                        to="tascrum.list",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberCardRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crole",
                        to="tascrum.card",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cmember",
                        to="tascrum.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="card",
            name="members",
            field=models.ManyToManyField(
                related_name="cmembers",
                through="tascrum.MemberCardRole",
                to="tascrum.member",
            ),
        ),
    ]
