# Generated by Django 4.2.6 on 2023-10-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0009_card_membercardrole_card_members"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="List",
            new_name="list",
        ),
    ]
