# Generated by Django 4.2.6 on 2023-10-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0010_rename_list_card_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='duedate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='card',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
