# Generated by Django 4.2.6 on 2023-10-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0010_rename_list_card_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="backgroundImage",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
