# Generated by Django 4.2.6 on 2023-10-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0011_board_backgroundimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="duedate",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="reminder",
            field=models.CharField(
                choices=[
                    ("At time of due date", "At time of due date"),
                    ("5 Minuets before", "5 Minuets before"),
                    ("10 Minuets before", "10 Minuets before"),
                    ("15 Minuets before", "15 Minuets before"),
                    ("1 Hour before", "1 Hour before"),
                    ("2 Hour before", "2 Hour before"),
                    ("1 Day before", "1 Day before"),
                    ("2 Days before", "2 Days before"),
                ],
                default="1 Day before",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="startdate",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="membercardrole",
            name="role",
            field=models.CharField(default="member", max_length=50),
        ),
    ]
