# Generated by Django 4.2.6 on 2023-10-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0012_alter_card_duedate_alter_card_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='duedate',
            field=models.DateTimeField(null=True),
        ),
    ]
