# Generated by Django 4.2.6 on 2023-10-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0016_alter_memberboardrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='backgroundimage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
