# Generated by Django 4.2.6 on 2023-11-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0018_burndownchart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="backgroundImage",
            field=models.ImageField(
                default="default_profile.png", null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="backgroundImage",
            field=models.ImageField(
                default="default_profile.png", null=True, upload_to="images/"
            ),
        ),
    ]
