# Generated by Django 4.2.6 on 2023-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0018_burndownchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='setestimate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='storypoint',
            field=models.IntegerField(default=0),
        ),
    ]
