# Generated by Django 4.2.6 on 2023-11-09 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0020_checklist_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chcard', to='tascrum.card'),
        ),
    ]
