# Generated by Django 4.2.6 on 2023-11-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0021_alter_checklist_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='backgroundimage',
            field=models.ImageField(default='default_profile.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='reminder',
            field=models.CharField(choices=[('At time of due date', 'At time of due date'), ('1 Day before', '1 Day before'), ('2 Day before', '2 Day before'), ('3 Day before', '3 Day before'), ('5 Days before', '5 Days before'), ('None', 'None')], default='1 Day before', max_length=30),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='backgroundimage',
            field=models.ImageField(default='default_profile.png', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Lable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blable', to='tascrum.board')),
            ],
        ),
    ]
