# Generated by Django 4.2.6 on 2023-11-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0023_board_lastseen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="lastseen",
        ),
        migrations.AddField(
            model_name="board",
            name="has_star",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="board",
            name="backgroundImage",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
