# Generated by Django 4.2.6 on 2023-11-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0024_remove_board_lastseen_board_has_star_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="lastseen",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="board",
            name="backgroundimage",
            field=models.ImageField(default="default_profile.png", upload_to="images/"),
        ),
    ]
