# Generated by Django 4.2.6 on 2023-11-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0026_alter_card_options_card_order"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="card",
            unique_together={("list", "order")},
        ),
    ]
