# Generated by Django 4.2.6 on 2023-11-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0028_alter_card_order"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="card",
            unique_together=set(),
        ),
    ]
