# Generated by Django 4.2.6 on 2023-11-19 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0029_alter_card_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardl', to='tascrum.card')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labelc', to='tascrum.lable')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='label',
            field=models.ManyToManyField(related_name='clabels', through='tascrum.CardLabel', to='tascrum.lable'),
        ),
    ]
