# Generated by Django 4.2.6 on 2023-11-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0029_alter_card_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="invitation_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
