# Generated by Django 4.2.6 on 2023-11-28 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0029_alter_card_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membercardrole",
            options={"ordering": ["member"]},
        ),
        migrations.RemoveField(
            model_name="burndownchart",
            name="user",
        ),
        migrations.AddField(
            model_name="board",
            name="invitation_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="burndownchart",
            name="board",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="burndown_charts",
                to="tascrum.board",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="burndownchart",
            name="member",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="burndown_charts",
                to="tascrum.member",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="burndownchart",
            name="done",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="burndownchart",
            name="estimate",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="lable",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boardl",
                to="tascrum.board",
            ),
        ),
        migrations.CreateModel(
            name="CardLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cardl",
                        to="tascrum.card",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labelc",
                        to="tascrum.lable",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
                "unique_together": {("card", "label")},
            },
        ),
        migrations.AddField(
            model_name="card",
            name="labels",
            field=models.ManyToManyField(
                related_name="clabel", through="tascrum.CardLabel", to="tascrum.lable"
            ),
        ),
    ]
