# Generated by Django 4.2.6 on 2023-11-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0030_question_board_invitation_link_alter_lable_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cardlabel',
            unique_together={('card', 'label')},
        ),
    ]
