# Generated by Django 4.2.6 on 2023-11-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0030_cardlabel_card_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='label',
            new_name='labels',
        ),
    ]
