# Generated by Django 4.2.6 on 2023-11-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0031_rename_label_card_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lable',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lableboard', to='tascrum.board'),
        ),
    ]
