# Generated by Django 4.2.6 on 2023-11-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0031_question_survey_surveyquestion_survey_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="status",
            field=models.CharField(
                choices=[
                    ("Done", "Done"),
                    ("overdue", "overdue"),
                    ("pending", "pending"),
                    ("failed", "failed"),
                ],
                default="pending",
                max_length=8,
            ),
        ),
    ]
