# Generated by Django 4.2.6 on 2023-11-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0031_card_description_alter_cardlabel_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membercardrole",
            options={"ordering": ["member"]},
        ),
    ]
