# Generated by Django 4.2.6 on 2023-11-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0032_alter_lable_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lable',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labelboard', to='tascrum.board'),
        ),
    ]
