# Generated by Django 4.2.6 on 2023-11-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0032_alter_cardlabel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membercardrole",
            options={"ordering": ["member"]},
        ),
    ]
