# Generated by Django 4.2.6 on 2023-12-14 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0033_meeting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={"ordering": ["time"]},
        ),
        migrations.AddField(
            model_name="meeting",
            name="title",
            field=models.CharField(default="meeting", max_length=255),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mboard",
                to="tascrum.board",
            ),
        ),
    ]
