# Generated by Django 4.2.6 on 2023-11-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0030_board_invitation_link'),
        ('tascrum', '0030_question_survey'),
        ('tascrum', '0034_alter_lable_board'),
    ]

    operations = [
    ]
