# Generated by Django 4.2.6 on 2023-12-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tascrum', '0035_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
