# Generated by Django 4.2.6 on 2023-12-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tascrum", "0036_card_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="backgroundImage",
            new_name="backgroundimage",
        ),
        migrations.RenameField(
            model_name="workspace",
            old_name="backgroundImage",
            new_name="backgroundimage",
        ),
    ]
